# ===========================================
# Database Configuration
# Project : 100 Days SDET Challenge
# Module  : Day-004 WMS User Authentication
# ===========================================

db.url=jdbc:mysql://localhost:3306/wms_db
db.username=root
db.password=root123
db.driver=com.mysql.cj.jdbc.Driver
